package api

import (
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"prompt-share-backend/middleware"
	"prompt-share-backend/service"

	"github.com/gin-gonic/gin"
	_ "prompt-share-backend/docs" // generated by swag
)

// InitRouter 初始化路由
func InitRouter() *gin.Engine {
	r := gin.Default()
	r.Use(middleware.Cors())
	r.Use(middleware.Logger())

	// health
	r.GET("/ping", func(c *gin.Context) { c.JSON(200, gin.H{"message": "pong"}) })

	// swagger
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// public
	public := r.Group("/api")
	{
		public.POST("/auth/register", Register)
		public.POST("/auth/login", Login)
		public.GET("/prompts", GetPrompts)
		public.GET("/prompts/:id", GetPrompt)
		public.GET("/files/:id", DownloadFile)
		public.GET("/prompts/:id/comments", ListComments)
	}

	// protected
	protected := r.Group("/api")
	//protected.Use(middleware.JWTAuth())
	{
		protected.POST("/prompts", CreatePrompt)
		protected.PUT("/prompts/:id", UpdatePrompt)
		protected.DELETE("/prompts/:id", DeletePrompt)
		protected.POST("/prompts/:id/like", LikePrompt)
		protected.POST("/prompts/:id/fav", FavoritePrompt)
		protected.POST("/prompts/:id/comments", CreateComment)
		protected.POST("/files/upload", UploadFile)
	}
	// init storage
	service.InitStorage()
	return r
}
